import { Hono } from 'hono'
import { SubscriberLayout } from '../../components/subscriber-layout'

type Bindings = { DB: D1Database }

const subscriberMethodologyRoutes = new Hono<{ Bindings: Bindings }>()

// ============================================================
// SUBSCRIBER — Methodology (Static)
// ============================================================
subscriberMethodologyRoutes.get('/methodology', (c) => {
  const user = c.get('user' as any) || null
  return c.html(
    <SubscriberLayout active="methodology" user={user}>
      <div class="fade-in">
        <div class="mb-8">
          <h1 class="text-2xl font-bold text-white">How We Generate <span class="text-[#d4a843] italic">Intelligence</span></h1>
          <p class="text-gray-400 text-sm mt-1">12 proprietary frameworks powering every alert, report, and watchlist entry</p>
        </div>

        {/* Dual-engine overview */}
        <div class="bg-[#111827] border border-[#1f2937] rounded-xl p-6 mb-8">
          <div class="flex items-center gap-2 mb-4">
            <i class="fas fa-microchip text-[#d4a843]"></i>
            <h2 class="text-lg font-bold text-white">Dual-Engine Intelligence Model</h2>
          </div>
          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div class="bg-[#0a0f1e] border border-[#1f2937] rounded-lg p-5">
              <div class="flex items-center gap-2 mb-3">
                <div class="w-8 h-8 bg-blue-500/20 rounded-lg flex items-center justify-center">
                  <i class="fas fa-bolt text-blue-400 text-sm"></i>
                </div>
                <h3 class="text-sm font-bold text-blue-400 uppercase tracking-wider">Engine 1: EPIG Alerts</h3>
              </div>
              <p class="text-gray-300 text-sm leading-relaxed">
                Real-time event-driven intelligence. Our Episodic Pivot Intelligence Generator scans thousands of data points daily to detect material events, stock dislocations, earnings surprises, and regime changes the moment they occur. Alerts are triaged by impact level and delivered within minutes of detection.
              </p>
            </div>
            <div class="bg-[#0a0f1e] border border-[#1f2937] rounded-lg p-5">
              <div class="flex items-center gap-2 mb-3">
                <div class="w-8 h-8 bg-[#d4a843]/20 rounded-lg flex items-center justify-center">
                  <i class="fas fa-microscope text-[#d4a843] text-sm"></i>
                </div>
                <h3 class="text-sm font-bold text-[#d4a843] uppercase tracking-wider">Engine 2: Research Portal</h3>
              </div>
              <p class="text-gray-300 text-sm leading-relaxed">
                Deep-dive analytical intelligence. The Research Portal houses weekly scorecards, multibagger reports, trend analysis, and structural risk assessments. Each output is generated by specialized AI agents running proprietary frameworks, then human-reviewed for accuracy and relevance before publication.
              </p>
            </div>
          </div>
        </div>

        {/* 12 Frameworks Grid */}
        <div class="mb-6">
          <div class="flex items-center gap-2 mb-4">
            <i class="fas fa-cubes text-[#d4a843]"></i>
            <h2 class="text-lg font-bold text-white">12 Proprietary Frameworks</h2>
          </div>
        </div>
        <div class="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4 mb-8" id="frameworks-grid">
          {/* 1. Material Events Research */}
          <div class="bg-[#111827] border border-[#1f2937] rounded-xl p-5 hover:border-[#d4a843]/30 transition-all">
            <div class="flex items-center gap-3 mb-3">
              <div class="w-10 h-10 bg-blue-500/20 rounded-lg flex items-center justify-center flex-shrink-0">
                <i class="fas fa-newspaper text-blue-400"></i>
              </div>
              <div>
                <h3 class="text-sm font-bold text-white">Material Events Research</h3>
                <span class="text-[10px] text-blue-400 uppercase tracking-wider">Feed &bull; Alerts</span>
              </div>
            </div>
            <p class="text-gray-400 text-xs leading-relaxed">Detects earnings surprises, M&A activity, FDA decisions, legal rulings, executive departures, and other material corporate events that fundamentally change a company's trajectory. Each event is scored for magnitude and whether it represents a genuine shift or noise.</p>
          </div>

          {/* 2. Stock Dislocation Detection */}
          <div class="bg-[#111827] border border-[#1f2937] rounded-xl p-5 hover:border-[#d4a843]/30 transition-all">
            <div class="flex items-center gap-3 mb-3">
              <div class="w-10 h-10 bg-rose-500/20 rounded-lg flex items-center justify-center flex-shrink-0">
                <i class="fas fa-chart-line text-rose-400"></i>
              </div>
              <div>
                <h3 class="text-sm font-bold text-white">Stock Dislocation Detection</h3>
                <span class="text-[10px] text-rose-400 uppercase tracking-wider">Feed &bull; Alerts</span>
              </div>
            </div>
            <p class="text-gray-400 text-xs leading-relaxed">Identifies 15-50%+ price drops driven by temporary catalysts rather than structural deterioration. Separates genuine dislocations (buying opportunities) from value traps by analyzing the root cause, business model integrity, and recovery probability within 6-18 months.</p>
          </div>

          {/* 3. Stock Doubler Identification */}
          <div class="bg-[#111827] border border-[#1f2937] rounded-xl p-5 hover:border-[#d4a843]/30 transition-all">
            <div class="flex items-center gap-3 mb-3">
              <div class="w-10 h-10 bg-orange-500/20 rounded-lg flex items-center justify-center flex-shrink-0">
                <i class="fas fa-rocket text-orange-400"></i>
              </div>
              <div>
                <h3 class="text-sm font-bold text-white">Stock Doubler Identification</h3>
                <span class="text-[10px] text-orange-400 uppercase tracking-wider">Research Reports</span>
              </div>
            </div>
            <p class="text-gray-400 text-xs leading-relaxed">Screens for companies with 100%+ appreciation potential over 12-24 months. Evaluates TAM expansion, competitive positioning, management quality, catalysts, and valuation gap. Only companies passing all five criteria receive a multibagger designation.</p>
          </div>

          {/* 4. Episodic Pivot Identification */}
          <div class="bg-[#111827] border border-[#1f2937] rounded-xl p-5 hover:border-[#d4a843]/30 transition-all">
            <div class="flex items-center gap-3 mb-3">
              <div class="w-10 h-10 bg-amber-500/20 rounded-lg flex items-center justify-center flex-shrink-0">
                <i class="fas fa-bolt text-amber-400"></i>
              </div>
              <div>
                <h3 class="text-sm font-bold text-white">Episodic Pivot Identification</h3>
                <span class="text-[10px] text-amber-400 uppercase tracking-wider">Feed &bull; Alerts</span>
              </div>
            </div>
            <p class="text-gray-400 text-xs leading-relaxed">Detects episodic pivot events that fundamentally change a company's trajectory. Classifies pivot type (earnings surprise, regulatory shift, management change, product inflection, macro regime), magnitude, and whether the market has fully priced the shift.</p>
          </div>

          {/* 5. Bias Mode Detection */}
          <div class="bg-[#111827] border border-[#1f2937] rounded-xl p-5 hover:border-[#d4a843]/30 transition-all">
            <div class="flex items-center gap-3 mb-3">
              <div class="w-10 h-10 bg-purple-500/20 rounded-lg flex items-center justify-center flex-shrink-0">
                <i class="fas fa-balance-scale text-purple-400"></i>
              </div>
              <div>
                <h3 class="text-sm font-bold text-white">Bias Mode Detection</h3>
                <span class="text-[10px] text-purple-400 uppercase tracking-wider">Feed &bull; Watchlist</span>
              </div>
            </div>
            <p class="text-gray-400 text-xs leading-relaxed">Triple-test framework that determines whether a stock's momentum is driven by genuine fundamentals or misleading signals. Separates real institutional accumulation from retail hype, and identifies when consensus narrative diverges from underlying data.</p>
          </div>

          {/* 6. Disruption & Superlative Detection */}
          <div class="bg-[#111827] border border-[#1f2937] rounded-xl p-5 hover:border-[#d4a843]/30 transition-all">
            <div class="flex items-center gap-3 mb-3">
              <div class="w-10 h-10 bg-emerald-500/20 rounded-lg flex items-center justify-center flex-shrink-0">
                <i class="fas fa-fire text-emerald-400"></i>
              </div>
              <div>
                <h3 class="text-sm font-bold text-white">Disruption &amp; Superlative Detection</h3>
                <span class="text-[10px] text-emerald-400 uppercase tracking-wider">Feed &bull; Avoid List</span>
              </div>
            </div>
            <p class="text-gray-400 text-xs leading-relaxed">Identifies disruptive products, technologies, and business models that create or destroy competitive moats. Scores disruption potential on a 10-point scale and maps which incumbents face existential threats versus which challengers are building durable advantages.</p>
          </div>

          {/* 7. Earnings Architecture Intelligence */}
          <div class="bg-[#111827] border border-[#1f2937] rounded-xl p-5 hover:border-[#d4a843]/30 transition-all">
            <div class="flex items-center gap-3 mb-3">
              <div class="w-10 h-10 bg-cyan-500/20 rounded-lg flex items-center justify-center flex-shrink-0">
                <i class="fas fa-building text-cyan-400"></i>
              </div>
              <div>
                <h3 class="text-sm font-bold text-white">Earnings Architecture Intelligence</h3>
                <span class="text-[10px] text-cyan-400 uppercase tracking-wider">Research Reports</span>
              </div>
            </div>
            <p class="text-gray-400 text-xs leading-relaxed">Deconstructs earnings quality beyond headline EPS. Analyzes revenue composition, margin trajectory, cash conversion, guide interpretation, and management credibility. Flags companies where reported earnings mask deteriorating fundamentals or understated strength.</p>
          </div>

          {/* 8. Catalyst Value Opportunity */}
          <div class="bg-[#111827] border border-[#1f2937] rounded-xl p-5 hover:border-[#d4a843]/30 transition-all">
            <div class="flex items-center gap-3 mb-3">
              <div class="w-10 h-10 bg-yellow-500/20 rounded-lg flex items-center justify-center flex-shrink-0">
                <i class="fas fa-gem text-yellow-400"></i>
              </div>
              <div>
                <h3 class="text-sm font-bold text-white">Catalyst Value Opportunity</h3>
                <span class="text-[10px] text-yellow-400 uppercase tracking-wider">Feed &bull; Watchlist</span>
              </div>
            </div>
            <p class="text-gray-400 text-xs leading-relaxed">Maps upcoming catalysts (earnings, product launches, regulatory decisions, conference presentations) against current valuation to identify asymmetric opportunities. Ranks catalyst probability, expected magnitude, and timing to flag the highest risk-reward setups.</p>
          </div>

          {/* 9. Counter-Trend Move Detection */}
          <div class="bg-[#111827] border border-[#1f2937] rounded-xl p-5 hover:border-[#d4a843]/30 transition-all">
            <div class="flex items-center gap-3 mb-3">
              <div class="w-10 h-10 bg-pink-500/20 rounded-lg flex items-center justify-center flex-shrink-0">
                <i class="fas fa-exchange-alt text-pink-400"></i>
              </div>
              <div>
                <h3 class="text-sm font-bold text-white">Counter-Trend Move Detection</h3>
                <span class="text-[10px] text-pink-400 uppercase tracking-wider">Feed &bull; Alerts</span>
              </div>
            </div>
            <p class="text-gray-400 text-xs leading-relaxed">Identifies stocks moving against their established trend on high conviction signals. Detects early reversals in extended rallies and capitulation bottoms in prolonged selloffs. Filters noise from signal by requiring multiple confirming indicators before flagging a counter-trend opportunity.</p>
          </div>

          {/* 10. S&P Correction Estimation */}
          <div class="bg-[#111827] border border-[#1f2937] rounded-xl p-5 hover:border-[#d4a843]/30 transition-all">
            <div class="flex items-center gap-3 mb-3">
              <div class="w-10 h-10 bg-red-500/20 rounded-lg flex items-center justify-center flex-shrink-0">
                <i class="fas fa-chart-area text-red-400"></i>
              </div>
              <div>
                <h3 class="text-sm font-bold text-white">S&amp;P Correction Estimation</h3>
                <span class="text-[10px] text-red-400 uppercase tracking-wider">Market Commentary</span>
              </div>
            </div>
            <p class="text-gray-400 text-xs leading-relaxed">Proprietary model estimating the probability, depth, and duration of S&amp;P 500 corrections. Combines technical indicators, credit spreads, sentiment extremes, and macro regime data to generate a forward-looking correction risk score updated weekly.</p>
          </div>

          {/* 11. Social Sentiment Scanner */}
          <div class="bg-[#111827] border border-[#1f2937] rounded-xl p-5 hover:border-[#d4a843]/30 transition-all">
            <div class="flex items-center gap-3 mb-3">
              <div class="w-10 h-10 bg-teal-500/20 rounded-lg flex items-center justify-center flex-shrink-0">
                <i class="fas fa-comments text-teal-400"></i>
              </div>
              <div>
                <h3 class="text-sm font-bold text-white">Social Sentiment Scanner</h3>
                <span class="text-[10px] text-teal-400 uppercase tracking-wider">Feed &bull; Trends</span>
              </div>
            </div>
            <p class="text-gray-400 text-xs leading-relaxed">Scans Reddit, X (Twitter), StockTwits, and financial forums for sentiment shifts, emerging narratives, and retail momentum before they appear in price action. Separates genuine grassroots conviction from coordinated campaigns and bot-driven hype.</p>
          </div>

          {/* 12. 5-Phase Parabolic Lifecycle */}
          <div class="bg-[#111827] border border-[#1f2937] rounded-xl p-5 hover:border-[#d4a843]/30 transition-all">
            <div class="flex items-center gap-3 mb-3">
              <div class="w-10 h-10 bg-indigo-500/20 rounded-lg flex items-center justify-center flex-shrink-0">
                <i class="fas fa-wave-square text-indigo-400"></i>
              </div>
              <div>
                <h3 class="text-sm font-bold text-white">5-Phase Parabolic Lifecycle</h3>
                <span class="text-[10px] text-indigo-400 uppercase tracking-wider">Watchlist &bull; Trends</span>
              </div>
            </div>
            <p class="text-gray-400 text-xs leading-relaxed">Maps every stock's position within the 5-phase parabolic lifecycle: Stealth, Awareness, Mania, Blow-Off, and Mean Reversion. Determines optimal entry/exit windows based on phase transitions and historical analogs. Prevents buying into blow-off tops or selling at stealth-phase lows.</p>
          </div>
        </div>

        {/* Human review emphasis */}
        <div class="bg-[#d4a843]/10 border border-[#d4a843]/20 rounded-xl p-6 mb-6">
          <div class="flex items-start gap-4">
            <div class="w-12 h-12 bg-[#d4a843]/20 rounded-full flex items-center justify-center flex-shrink-0">
              <i class="fas fa-user-check text-[#d4a843] text-lg"></i>
            </div>
            <div>
              <h3 class="text-base font-bold text-[#d4a843] mb-2">All Intelligence Is Human-Reviewed Before Publication</h3>
              <p class="text-gray-300 text-sm leading-relaxed">
                Every alert, report, scorecard, and watchlist update generated by our AI agents undergoes human review before reaching subscribers. Our analysts verify data accuracy, challenge AI conclusions, and ensure all outputs meet our quality threshold. This hybrid approach combines the speed and breadth of AI with the judgment and accountability of experienced analysts.
              </p>
            </div>
          </div>
        </div>

        {/* Compliance disclaimer */}
        <div class="bg-[#111827] border border-[#1f2937] rounded-xl p-5">
          <div class="flex items-center gap-2 mb-3">
            <i class="fas fa-shield-alt text-gray-500 text-sm"></i>
            <h3 class="text-xs font-semibold text-gray-500 uppercase tracking-wider">Important Disclosures</h3>
          </div>
          <div class="text-[11px] text-gray-500 leading-relaxed space-y-2">
            <p>All content provided through the Ekantik Research Intelligence Portal is for educational and informational purposes only. Nothing herein constitutes investment advice, a solicitation, or a recommendation to buy or sell any security or financial instrument.</p>
            <p>The AI-generated research, scores, and ratings are outputs of proprietary models and should not be relied upon as the sole basis for any investment decision. All investments carry risk, including the potential loss of principal. Past performance does not guarantee future results.</p>
            <p>EPIG performance targets and multibagger designations are goals based on backtested methodology and forward-looking analysis. They are not guaranteed outcomes. Individual results will vary based on timing, position sizing, and market conditions.</p>
            <p>Ekantik Capital Advisors and its principals may hold positions in securities discussed in this portal. Always conduct your own due diligence and consult a licensed financial advisor before making investment decisions.</p>
          </div>
        </div>
      </div>
    </SubscriberLayout>
  )
})


export { subscriberMethodologyRoutes }
